spring.application.name=ocorrencias
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
#spring.profiles.active=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=${PORTA}
spring.jpa.hibernate.ddl-auto=update

token.whatsapp=${TOKEN_WHATSAPP}
id.conta=${ID_CONTA}
id.canal=${ID_CANAL}
id.flow.resposta=${ID_FLOW_RESPOSTA}
