name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  testes:
    name: Testes
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./Projeto_ocorrencias_API

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Dar permissão ao mvnw
        run: chmod +x ./mvnw
        working-directory: ./Projeto_ocorrencias_API

      - name: Executar Testes JUnit
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          PORTA: ${{ secrets.PORTA }}
          TOKEN_WHATSAPP: ${{ secrets.TOKEN_WHATSAPP }}
          ID_CONTA: ${{ secrets.ID_CONTA }}
          ID_CANAL: ${{ secrets.ID_CANAL }}
          ID_FLOW_RESPOSTA: ${{ secrets.ID_FLOW_RESPOSTA }}
        run: ./mvnw test

  deploy:
    name: Deploy no Render
    needs: testes
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://projeto-ocorrencias-ssw.onrender.com # 👈 troca pela URL real

    steps:
      - name: Acionar deploy no Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
