name: CI/CD no Meu Computador

on:
  push:
    branches: [ main ]

jobs:
  deploy-local:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./Projeto_ocorrencias_API

    steps:
      - name: Baixar código do GitHub
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # - name: Criar arquivo .env
      #  shell: powershell
      #  run: |
      #    $content = @(
      #    "PORTA=${{ secrets.PORTA }}",
      #    "DB_URL=${{ secrets.DB_URL }}",
      #    "DB_USER=${{ secrets.DB_USER }}",
      #    "DB_PASS=${{ secrets.DB_PASS }}",
      #    "TOKEN_WHATSAPP=${{ secrets.TOKEN_WHATSAPP }}",
      #    "ID_CONTA=${{ secrets.ID_CONTA }}",
      #    "ID_CANAL=${{ secrets.ID_CANAL }}",
      #    "ID_FLOW_RESPOSTA=${{ secrets.ID_FLOW_RESPOSTA }}"
      #    )
      #   [System.IO.File]::WriteAllLines("$(Get-Location)/.env", $content)
      - name: Verificar .env gerado
        shell: powershell
        run: Get-Content .env

      - name: Executar Testes JUnit
        shell: powershell
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          PORTA: ${{ secrets.PORTA }}
          TOKEN_WHATSAPP: ${{ secrets.TOKEN_WHATSAPP }}
          ID_CONTA: ${{ secrets.ID_CONTA }}
          ID_CANAL: ${{ secrets.ID_CANAL }}
          ID_FLOW_RESPOSTA: ${{ secrets.ID_FLOW_RESPOSTA }}
        run: ./mvnw test

      - name: Build e Deploy no Docker
        run: docker-compose up -d --build
